export const CREATE_PODCAST_SUCCESS = 'CREATE_PODCAST_SUCCESS';
export const LOAD_PODCASTS_SUCCESS = 'LOAD_PODCASTS_SUCCESS';
export const UPDATE_PODCAST_SUCCESS = 'UPDATE_PODCAST_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const DELETE_PODCAST = 'DELETE_PODCAST';
